backend:
  name: git-gateway
  branch: master
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Index Page"
        name: "index"
        file: "index.html"
        fields:
            - {label: "Heading", name: "indexh1", widget: "text"}
            - {label: "DataIndex", name: "indexdata", widget: "text"}
media_folder: assets/uploads