backend:
  name: git-gateway
  branch: master
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Index Page"
        name: "index"
        file: "index.html"
        
media_folder: assets/uploads