backend:
  name: git-gateway
  branch: main
collections:
  - name: "pages"
    label: "Pages"
    extension: "json"
    files:
      - label: "Setting"
        name: "setting"
        file: "people.json"
        fields:
            - {label: "FirstName", name: "firstName", widget: code}
            - {label: "LastName", name: "lastName", widget: code}
            - {label: "Email", name: "email", widget: code}
            - {label: "City", name: "city", widget: code}
media_folder: assets/uploads