backend:
  name: github
  repo: https://github.com/nikhilj21/testnetlify
  branch: master
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Index Page"
        name: "index"
        file: "index.html"
        fields:
            - {label: "Heading", name: "indexh1"}
            - {label: "DataIndex", name: "indexdata"}
media_folder: assets/uploads