backend:
  name: testnetlify
  branch: master
publish_mode: editorial_workflow
collections:
  - name: "heading1"
    label: "Heading1"
    widget: "string"
    extension: "html"
    file: "page1.html"
    folder: "/"
media_folder: assets/uploads