backend:
  name: git-gateway
  branch: master
collections:
  - name: "index" # Used in routes, e.g., /admin/collections/blog
    label: "Index" # Used in the UI
    fields: # The fields for each document, usually in front matter
      - {label: "Heading", name: "indexh1", widget: "string"}
      - {label: "DataIndex", name: "indexdata", widget: "string"}
media_folder: assets/uploads