backend:
  name: git-gateway
  branch: main
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Index Page"
        name: "indexh1"
        file: "index.html"
        fields:
            - {label: "Heading", name: "indexh1"}
            - {label: "DataIndex", name: "indexdata"}
media_folder: assets/uploads