backend:
  name: git-gateway
  branch: main
collections:
  - name: "pages"
    label: "Pages"
    extension: "json"
    files:
      - label: "Setting"
        name: "setting"
        file: "people.json"
        fields:
          - label: "Person"
            name: "person"
            widget: "list"
            fields:
              - {label: "FirstName", name: "firstName", widget: "string"}
              - {label: "LastName", name: "lastName", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}
              - {label: "City", name: "city", widget: "string"}
media_folder: assets/uploads